#!/bin/bash

ProgName=AbinitGUI

Des=./Prog

[ -d $Des ] && echo 'Folder '$Des' exists!' || mkdir $Des

Dest=../$Des

LIBS=$Dest

LOG=../AbinitGUI.log

OPTS='-nowarn -O -verbose'

cd src;

# Compile ISNETWORKS, JCRAFT, MINDBRIGHT
echo "Compilation of the ISNETWORKS, JCRAFT, and MINDBRIGHT library..."
javac $OPTS -d $Dest ./com/isnetworks/ssh/*.java 2> $LOG
javac $OPTS -d $Dest ./com/jcraft/jsch/*.java 2> $LOG
javac $OPTS -d $Dest ./com/jcraft/jsch/jce/*.java 2> $LOG
javac $OPTS -d $Dest ./com/jcraft/jsch/jcraft/*.java 2> $LOG
javac $OPTS -d $Dest ./com/jcraft/jsch/jgss/*.java 2> $LOG
javac $OPTS -d $Dest ./com/jcraft/jzlib/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/application/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/asn1/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/bdb/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/gui/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/jce/provider/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/jce/provider/ciphers/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/jce/provider/digests/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/jce/provider/hmacs/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/jce/provider/keystore/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/jce/provider/prng/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/jce/provider/publickey/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/net/ftp/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/net/telnet/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/nio/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/security/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/security/ms/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/security/pkcs1/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/security/pkcs12/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/security/pkcs6/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/security/pkcs7/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/security/pkcs8/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/security/x509/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/ssh/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/ssh2/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/sshcommon/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/terminal/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/terminal/filter/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/terminal/tandem6530/*.java 2> $LOG
javac $OPTS -d $Dest ./com/mindbright/util/*.java 2> $LOG
echo "ISNETWORKS, JCRAFT, and MINDBRIGHT library compiled."

# Compile swing-layout
echo "Compilation of the swing-layout library..."
javac $OPTS -d $Dest ./org/jdesktop/layout/*.java 2>> $LOG
echo "Swing-layout library compiled."

# Compile JDOM
echo "Compilation of the JDOM library..."
javac $OPTS -d $Dest ./org/jdom/*.java 2>> $LOG
javac $OPTS -d $Dest ./org/jdom/adapters/*.java 2>> $LOG
javac $OPTS -d $Dest ./org/jdom/filter/*.java 2>> $LOG
javac $OPTS -d $Dest ./org/jdom/input/*.java 2>> $LOG
javac $OPTS -d $Dest ./org/jdom/output/*.java 2>> $LOG
javac $OPTS -d $Dest ./org/jdom/transform/*.java 2>> $LOG
echo "JDOM library compiled."

# Compile AbinitGUI
echo "Compilation of the AbinitGUI program..."
javac $OPTS -d $Dest -cp $LIBS ./abinitgui/*.java 2>> $LOG
javac $OPTS -d $Dest -cp $LIBS ./Main.java 2>> $LOG
echo "AbinitGUI program compiled."

cd $Dest

# Création de l'exécutable AbinitGUI.jar
echo "JAR file creation..."
jar -cfe0 $ProgName.jar Main *
echo "JAR file created."

chmod +x $ProgName.jar
mv $ProgName.jar ../$ProgName.jar
