/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package abinitgui.scriptbib;

import abinitgui.core.LocalExec;
import abinitgui.core.MainFrame;
import abinitgui.core.RetMSG;
import abinitgui.core.Utils;
import abinitgui.projects.Machine;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author yannick
 */
public class PostProcPanel extends javax.swing.JPanel {
    
    
    private DefaultListModel scriptModel;
    private final ScriptBib scriptBibs;
    private final ScriptTableModel argsModel;
    private final ScriptTableModel outModel;
    private Machine currentMachineForScript;

    /**
     * Creates new form PostProcPanel
     */
    public PostProcPanel() {
        initComponents();
        scriptBibs = new ScriptBib();
        outModel = new ScriptTableModel(scriptOutTable);
        
        scriptOutTable.setModel(outModel);
        initTableHeader(scriptOutTable, new String[]{"Name", "Value"},
                new Integer[]{null, null});
        scriptOutTable.setDefaultRenderer(ScriptArgument.class,
                new ScriptArgumentRenderer());
        
        argsModel = new ScriptTableModel(scriptArgTable);

        scriptArgTable.setModel(argsModel);
        initTableHeader(scriptArgTable, new String[]{"Name", "Value"},
                new Integer[]{null, null});
        scriptArgTable.setDefaultRenderer(ScriptArgument.class,
                new ScriptArgumentRenderer());
    }
    
    public void refresh() {

        /**
         * Script section *
         */
        
        if(Utils.exists("listScripts.xml"))
        {
            scriptBibs.loadScriptsFromFile("listScripts.xml");
        } else {
            MainFrame.printERR("No file listScripts.xml in the directory: you won't"
                    + " be able to use post-processing tools.");
        }

        scriptModel = new DefaultListModel();
        scriptList.setModel(scriptModel);

        showScripts();
    }
    
    private void initTableHeader(JTable table, String header[], Integer headerWidths[]) {
        TableColumnModel tcm = new DefaultTableColumnModel();
        for (int i = 0; i < header.length; i++) {
            TableColumn tc = new TableColumn(i);
            tc.setHeaderValue(header[i]);
            tc.setResizable(false);
            if (headerWidths[i] != null) {
                tc.setMinWidth(headerWidths[i]);
                tc.setPreferredWidth(headerWidths[i]);
                tc.setMaxWidth(headerWidths[i]);
            }
            tcm.addColumn(tc);
        }
        table.setColumnModel(tcm);
    }
    
    
    
    public final void refreshMachines()
    {        
        Machine mymach2 = (Machine)(machineCombo1.getSelectedItem());
        
        DefaultComboBoxModel<Machine> model2 = new DefaultComboBoxModel<>();
        
        for(Machine mach : MainFrame.getMachineDatabase())
        {
            model2.addElement(mach);
        }
        
        machineCombo1.setModel(model2);
        machineCombo1.setSelectedItem(mymach2);
    }
    
    private void showScripts() {
        scriptList.clearSelection();
        scriptModel.clear();

        ArrayList<Script> list = scriptBibs.getList();
        int nbScripts = list.size();

        String strName[] = new String[nbScripts];

        for (int i = 0; i < nbScripts; i++) {
            Script scr = list.get(i);

            strName[i] = scr.title;
        }

        scriptList.setListData(strName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scriptScrollPane = new javax.swing.JScrollPane();
        scriptList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        scriptName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scriptDescription = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        scriptArgTable = new ScriptTable();
        launchScript = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        scriptOutTable = new ScriptTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        scriptProgram = new javax.swing.JTextField();
        openOutput = new javax.swing.JButton();
        editScripts = new javax.swing.JButton();
        reloadScripts = new javax.swing.JButton();
        machineCombo1 = new javax.swing.JComboBox();
        machineLabel1 = new javax.swing.JLabel();

        scriptList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scriptList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                scriptListValueChanged(evt);
            }
        });
        scriptScrollPane.setViewportView(scriptList);

        jLabel1.setText("Name of the script :");

        scriptName.setText("Name");

        jLabel3.setText("Description : ");

        scriptDescription.setEditable(false);
        scriptDescription.setColumns(20);
        scriptDescription.setLineWrap(true);
        scriptDescription.setRows(5);
        scriptDescription.setText("Description of the script");
        scriptDescription.setWrapStyleWord(true);
        jScrollPane1.setViewportView(scriptDescription);

        jLabel5.setText("Arguments :");

        scriptArgTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(scriptArgTable);

        launchScript.setText("Launch script !");
        launchScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchScriptActionPerformed(evt);
            }
        });

        scriptOutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(scriptOutTable);

        jLabel6.setText("Output files :");

        jLabel9.setText("Program :");

        scriptProgram.setEditable(false);
        scriptProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scriptProgramActionPerformed(evt);
            }
        });

        openOutput.setText("Open output files !");
        openOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openOutputActionPerformed(evt);
            }
        });

        editScripts.setText("Edit script");
        editScripts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editScriptsActionPerformed(evt);
            }
        });

        reloadScripts.setText("Reload scripts");
        reloadScripts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadScriptsActionPerformed(evt);
            }
        });

        machineCombo1.setModel(new DefaultComboBoxModel<Machine>());
        machineCombo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                machineCombo1ItemStateChanged(evt);
            }
        });
        machineCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machineCombo1ActionPerformed(evt);
            }
        });

        machineLabel1.setText("Select machine on which running the simulation :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scriptScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(editScripts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reloadScripts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(machineLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(154, 154, 154)
                                        .addComponent(machineCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(scriptName, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(scriptProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(launchScript, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(openOutput)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(machineLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(machineCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(scriptName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(scriptProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(launchScript)
                            .addComponent(openOutput)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scriptScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editScripts)
                        .addGap(3, 3, 3)
                        .addComponent(reloadScripts)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void scriptListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_scriptListValueChanged
        int index = scriptList.getSelectedIndex();
        if (index < 0) {
            scriptName.setText("Name");
            scriptDescription.setText("Description of the script");
            scriptProgram.setText("");
            argsModel.resetScripts();
            outModel.resetScripts();
        } else {
            Script scr = scriptBibs.getList().get(index);
            if (scr == null) {
                scriptName.setText("Name");
                scriptDescription.setText("Description of the script");
                scriptProgram.setText("");
                argsModel.resetScripts();
                outModel.resetScripts();
                return;
            }

            scriptName.setText(scr.title);

            scriptDescription.setText(scr.description.replace("\\n", "\n"));

            scriptProgram.setText(scr.program);
            argsModel.resetScripts();
            outModel.resetScripts();

            ArrayList<ScriptArgument> listArgs = scr.listArgs;

            int nbArgs = listArgs.size();

            for (int i = 0; i < nbArgs; i++) {
                argsModel.addScript(listArgs.get(i));
            }

            ArrayList<ScriptArgument> outArgs = scr.listOutput;

            int nbOut = outArgs.size();

            for (int i = 0; i < nbOut; i++) {
                outModel.addScript(outArgs.get(i));
            }
        }
    }//GEN-LAST:event_scriptListValueChanged

    private void launchScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchScriptActionPerformed

        Runnable r = new Runnable() {
            @Override
            public void run() {

                Machine mach = currentMachineForScript;

                if(mach == null)
                {
                    MainFrame.printERR("Please select a machine first");
                    return;
                }

                String rootPath = mach.getSimulationPath();

                String folder = "scripts";

                String path = mach.getSimulationPath();
                if (path.equals("")) {
                    path = ".";
                }

                MainFrame.getLocalExec().createTree(path);

                int index = scriptList.getSelectedIndex();

                if (index == -1) {
                    MainFrame.printERR("Please select a script before running");
                    return;
                }

                Script scr = scriptBibs.getList().get(index);

                if (scr == null) {
                    MainFrame.printERR("Please select a script before running");
                    return;
                }

                String inputFile = scr.fileName;

                String program = scr.program;

                // +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

                if (Utils.osName().startsWith("Windows") || Utils.osName().startsWith("MAC")) {
                    MainFrame.printERR("Scripts are not supported for Windows platform yet");
                    launchScript.setEnabled(true);
                    return;
                }

                // ********************************************************************************************************************************

                String cwd = "";

                String CMD = "pwd";
                
                LocalExec localExec = MainFrame.getLocalExec();

                RetMSG retmsg;

                retmsg = localExec.sendCommand(CMD);
                if (retmsg.getRetCode() == RetMSG.SUCCES) {
                    MainFrame.printOUT("PWD: " + retmsg.getRetMSG());
                    cwd = Utils.removeEndl(retmsg.getRetMSG());
                } else {
                    MainFrame.printERR("Error: " + retmsg.getRetMSG() + " !");
                }

                String inputFileName = Utils.getLastToken(inputFile.replace('\\', '/'), "/");

                // Test de l'existance de inputfile
                if (!Utils.exists(inputFile)) {
                    MainFrame.printERR("The file " + inputFile + " doesn't exist!");
                    launchScript.setEnabled(true);
                    return;
                }

                if (!inputFile.equals("")) {
                    // Will do the computation in rootpath/folder
                    String inputFileR = rootPath + "/" + folder + "/" + inputFileName;
                    retmsg = localExec.sendCommand("cp "+inputFile+" "+inputFileR);
                    if (retmsg.getRetCode() != RetMSG.SUCCES) {
                        MainFrame.printERR("Error: " + retmsg.getRetMSG() + "!");
                    }

                    ArrayList<String> allCommand = new ArrayList<>();
                    ArrayList<ScriptArgument> listArgs = scr.listArgs;
                    allCommand.add(program);
                    allCommand.add(inputFileR);

                    String command = program + " " + inputFileR;

                    for (int i = 0; i < listArgs.size(); i++) {
                        String input = (String) scriptArgTable.getValueAt(i, 1);
                        command = command + " --" + listArgs.get(i).name + " \'" + input + "\'";
                        allCommand.add("--" + listArgs.get(i).name );
                        allCommand.add(input);
                    }

                    System.out.println("CWD = "+cwd);

                    ArrayList<ScriptArgument> listOut = scr.listOutput;

                    for (int i = 0; i < listOut.size(); i++) {
                        String outFile = (String) scriptOutTable.getValueAt(i, 1);
                        //                        String outFileR = rootPath + "/" + folder + "/" + outFile;
                        command = command + " --" + listOut.get(i).name + " \'" + outFile + "\'";
                        allCommand.add("--" + listOut.get(i).name);
                        allCommand.add(outFile);
                    }

                    String[] arrayCMD = allCommand.toArray(new String[0]);
                    retmsg = localExec.sendCommand(arrayCMD);
                    if (retmsg.getRetCode() == RetMSG.SUCCES) {
                        MainFrame.printOUT("Script output : \n"+retmsg.getRetMSG());
                    } else {
                        MainFrame.printERR("Error: " + retmsg.getRetMSG() + "!");
                    }
                    MainFrame.printDEB(command);

                }

            }
        };

        Thread t = new Thread(r);
        t.start();
    }//GEN-LAST:event_launchScriptActionPerformed

    private void scriptProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scriptProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scriptProgramActionPerformed

    private void openOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openOutputActionPerformed

        Machine mach = currentMachineForScript;
        if(mach == null)
        {
            MainFrame.printERR("Please select a machine first");
        }

        int index = scriptList.getSelectedIndex();
        if (index < 0) {
            return;
        }

        Script scr = scriptBibs.getList().get(index);
        if (scr == null) {
            return;
        }

        ArrayList<ScriptArgument> listOut = scr.listOutput;

        String rootPath;
        if(mach != null) {
            rootPath = mach.getSimulationPath();
        } else {
            // TODO: error report
            rootPath = "";
        }

        // Open files
        for (int i = 0; i < listOut.size(); i++) {
            String outFile = (String) scriptOutTable.getValueAt(i, 1);
            //String outFileR = rootPath + "/" + folder + "/" + outFile;

            File f = new File(rootPath);

            if (!f.exists()) {
                MainFrame.getLocalExec().createTree(rootPath);
                f = new File(rootPath);
            }

            String abs = "";
            try {
                abs = f.getCanonicalPath();
            } catch (IOException ex) {
                MainFrame.printERR("Unable to get output file canonical path");
                return;
            }

            f = new File(outFile);

            MainFrame.printOUT("Trying to open file : " + outFile);
            if (f.exists()) {
                try {
                    if (Desktop.isDesktopSupported()) {
                        if (Utils.osName().contains("Windows")) {
                            if (outFile.endsWith(".txt") || outFile.endsWith(".dbs") || outFile.endsWith(".agr")
                                || outFile.endsWith(".files") || outFile.endsWith(".in") || outFile.endsWith(".out")
                                || outFile.endsWith(".sh")) {
                                MainFrame.editFile(outFile, true);
                            } else {
                                Desktop.getDesktop().open(f);
                            }
                        } else {
                            Desktop.getDesktop().open(f);
                        }
                    } else {
                        MainFrame.printOUT("Not able to open the file with the default editor. Use basic editor instead.");
                        MainFrame.editFile(outFile, true);
                    }
                } catch (IOException ex) {
                    MainFrame.printOUT("Not able to open the file with the default editor. Use editor instead.");
                    MainFrame.editFile(outFile, true);
                }
            } else {
                MainFrame.printERR("Please execute the script before opening the output files.");
            }

        }
    }//GEN-LAST:event_openOutputActionPerformed

    private void editScriptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editScriptsActionPerformed
        int idScript = scriptList.getSelectedIndex();

        if (idScript == -1) {
            MainFrame.printERR("Please select a script first!");
        } else {
            Script scr = scriptBibs.getList().get(idScript);

            String inputFile = scr.fileName;

            if (Utils.osName().startsWith("Windows")) {
                Utils.unix2dos(new File(inputFile));
            }
            MainFrame.editFile(inputFile, true);
        }
    }//GEN-LAST:event_editScriptsActionPerformed

    private void reloadScriptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadScriptsActionPerformed
        scriptBibs.getList().clear();
        scriptBibs.loadScriptsFromFile("listScripts.xml");
        showScripts();
    }//GEN-LAST:event_reloadScriptsActionPerformed

    private void machineCombo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_machineCombo1ItemStateChanged

    }//GEN-LAST:event_machineCombo1ItemStateChanged

    private void machineCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machineCombo1ActionPerformed
        Machine mach = (Machine)machineCombo1.getSelectedItem();
        if(mach != null)
        {
            this.currentMachineForScript = mach;
        }
    }//GEN-LAST:event_machineCombo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editScripts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton launchScript;
    private javax.swing.JComboBox machineCombo1;
    private javax.swing.JLabel machineLabel1;
    private javax.swing.JButton openOutput;
    private javax.swing.JButton reloadScripts;
    private javax.swing.JTable scriptArgTable;
    private javax.swing.JTextArea scriptDescription;
    private javax.swing.JList scriptList;
    private javax.swing.JLabel scriptName;
    private javax.swing.JTable scriptOutTable;
    private javax.swing.JTextField scriptProgram;
    private javax.swing.JScrollPane scriptScrollPane;
    // End of variables declaration//GEN-END:variables
}
