/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package abjmol;

import org.openscience.jmol.app.jmolpanel.console.AppConsole;

/**
 *
 * @author yannick
 */
public class JMolPreview extends javax.swing.JPanel {
    
    private AppConsole console;

    /**
     * Creates new form JMolPane
     */
    public JMolPreview() {
        initComponents();
        
        //String strError = jMolPanel1.getViewer()
        //    .openFile("http://chemapps.stolaf.edu/jmol/docs/examples-11/data/zircon.xyz");
    }
    
    public void setMolecule(String XYZFile) {
        jMolPanel1.getViewer()
            .openFile(XYZFile);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMolPanel1 = new abjmol.JMolPanel();

        javax.swing.GroupLayout jMolPanel1Layout = new javax.swing.GroupLayout(jMolPanel1);
        jMolPanel1.setLayout(jMolPanel1Layout);
        jMolPanel1Layout.setHorizontalGroup(
            jMolPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jMolPanel1Layout.setVerticalGroup(
            jMolPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMolPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMolPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private abjmol.JMolPanel jMolPanel1;
    // End of variables declaration//GEN-END:variables

}
