/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package MDandTB;

import core.MainFrame;
import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import projects.Simulation;
import projects.SimulationPanel;

/**
 *
 * @author yannick
 */
public class TightBindingPanelOld extends SimulationPanel {

    private MainFrame mf;
    
    /**
     * Creates new form TightBindingPanel
     */
    public TightBindingPanelOld() {
        initComponents();
    }
    
    public void setMainFrame(MainFrame mf)
    {
        this.mf = mf;
    }
    
    @Override
    public void fillFromSimu(Simulation currentSimu) {
        if(currentSimu instanceof TightBindingSimulationOld)
        {
            TightBindingSimulationOld simu = (TightBindingSimulationOld)currentSimu;
            
            jRB_model1.setSelected(simu.getModel() == 1);
            jRB_model2.setSelected(simu.getModel() == 2);
            LTextField.setText(""+simu.getL());
            MTextField.setText(""+simu.getM());
            NkptTextField.setText(""+simu.getNkpt());
        }
        else
        {
            throw new UnsupportedOperationException("Not able to tackle simulation");
        }
    }

    @Override
    public void fillSimu(Simulation currentSimu) {
        
        if(currentSimu instanceof TightBindingSimulationOld)
        {
            TightBindingSimulationOld simu = (TightBindingSimulationOld)currentSimu;
            
            if(jRB_model1.isSelected())
            {
                simu.setModel(1);
            }
            else if(jRB_model2.isSelected())
            {
                simu.setModel(2);
            }
            simu.setL(Integer.parseInt(LTextField.getText()));
            simu.setM(Integer.parseInt(MTextField.getText()));
            simu.setNkpt(Integer.parseInt(NkptTextField.getText()));
            
        }
        else
        {
            throw new UnsupportedOperationException("Not able to tackle simulation");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel14 = new javax.swing.JPanel();
        LLabel2 = new javax.swing.JLabel();
        LTextField = new javax.swing.JTextField();
        MLabel2 = new javax.swing.JLabel();
        MTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRB_model1 = new javax.swing.JRadioButton();
        jRB_model2 = new javax.swing.JRadioButton();
        NkptLabel = new javax.swing.JLabel();
        NkptTextField = new javax.swing.JTextField();

        jPanel14.setBackground(new java.awt.Color(0, 102, 204));

        LLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        LLabel2.setText("L");

        LTextField.setText("3");

        MLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        MLabel2.setText("M");

        MTextField.setText("3");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("MODEL");

        buttonGroup2.add(jRB_model1);
        jRB_model1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jRB_model1.setSelected(true);
        jRB_model1.setText("1");
        jRB_model1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_model1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRB_model2);
        jRB_model2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jRB_model2.setText("2");

        NkptLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        NkptLabel.setText("Number of k-points");

        NkptTextField.setText("20");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(LLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB_model1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB_model2))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(NkptLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NkptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LLabel2)
                        .addComponent(LTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MLabel2)
                        .addComponent(MTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jRB_model1)
                        .addComponent(jRB_model2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NkptLabel)
                    .addComponent(NkptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRB_model1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_model1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_model1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LLabel2;
    private javax.swing.JTextField LTextField;
    private javax.swing.JLabel MLabel2;
    private javax.swing.JTextField MTextField;
    private javax.swing.JLabel NkptLabel;
    private javax.swing.JTextField NkptTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JRadioButton jRB_model1;
    private javax.swing.JRadioButton jRB_model2;
    // End of variables declaration//GEN-END:variables
}
